import type { GalleryImage } from '@/content/types'

const galleryImageOrigin = 'https://images.dominicgiarrusso.com'

const galleryImageTransforms = {
  thumbnail:
    'fit=scale-down,width=1200,quality=80,format=auto,metadata=copyright',
  full: 'fit=scale-down,width=2560,quality=88,format=auto,metadata=copyright',
} as const

function getGalleryImageUrl(
  objectKey: string,
  transform: keyof typeof galleryImageTransforms,
): string {
  const normalizedObjectKey = objectKey.replace(/^\/+/, '')

  return `${galleryImageOrigin}/cdn-cgi/image/${galleryImageTransforms[transform]}/${normalizedObjectKey}`
}

const photoImagePath = 'gallery/photos'
const japan2023PhotoImagePath = `${photoImagePath}/jp2023`
const artImagePath = 'gallery/art'

function getPhotoImageUrls(
  filename: string,
  imagePath = photoImagePath,
): Pick<GalleryImage, 'thumbnailUrl' | 'fullUrl'> {
  const objectKey = `${imagePath}/${filename}`

  return {
    thumbnailUrl: getGalleryImageUrl(objectKey, 'thumbnail'),
    fullUrl: getGalleryImageUrl(objectKey, 'full'),
  }
}

function getArtImageUrls(
  filename: string,
): Pick<GalleryImage, 'thumbnailUrl' | 'fullUrl'> {
  return getPhotoImageUrls(filename, artImagePath)
}

const artImages: Array<GalleryImage> = [
  {
    id: 'yeti-mouth-games-logo',
    title: 'Yeti Mouth Games Logo',
    alt: 'A blue cartoon monster mouth surrounding the words Yeti Mouth Games.',
    ...getArtImageUrls('YMGLogoTextT3.png'),
    variant: 'big',
    width: 900,
    height: 900,
  },
  {
    id: 'stroll-through-mason',
    title: 'Stroll through Mason',
    alt: 'A green collage poster combining George Mason University buildings, landmarks, and footprints.',
    ...getArtImageUrls('STM.jpg'),
    variant: 'square',
    width: 2550,
    height: 3300,
  },
  {
    id: 'local-artist-showcase-poster',
    title: 'Local Artist Showcase Poster',
    alt: 'A black-and-white event poster with geometric shapes, a concert photo, and George Mason University scenery.',
    ...getArtImageUrls('LocalArtistShowcasePoster.jpg'),
    variant: 'square',
    width: 2529,
    height: 2756,
  },
  {
    id: 'm-for-medieval',
    title: 'M for Medieval',
    alt: 'A blue poster with a low-poly castle illustration and text about the medieval period.',
    ...getArtImageUrls('GiarrussoDominic_Lowpoly-1.png'),
    variant: 'tall',
    width: 2074,
    height: 2820,
  },
  {
    id: 'earth-3d-render',
    title: 'Earth (3D Render)',
    alt: 'A digital rendering of Earth floating against a black star field.',
    ...getArtImageUrls('Earth.png'),
    variant: 'big',
    width: 1920,
    height: 1080,
  },

  {
    id: 'f-for-fantasy',
    title: 'F for Fantasy',
    alt: 'An orange poster with a low-poly castle illustration and a definition of fantasy.',
    ...getArtImageUrls('GiarrussoDominic_Lowpoly-2.png'),
    variant: 'square',
    width: 2074,
    height: 2820,
  },

  {
    id: 'mountains-3d-render',
    title: 'Mountains! (3D Render)',
    alt: 'A digitally rendered mountain range covered in evergreen forest and low mist.',
    ...getArtImageUrls('Finalmountains.png'),
    variant: 'wide',
    width: 3840,
    height: 2160,
  },
  {
    id: 'rocky-mountain-lakes-3d-render',
    title: 'Rocky Mountain Lakes (3D Render)',
    alt: 'A digitally rendered rocky mountain range rising above a broad lake.',
    ...getArtImageUrls('Digitallandscape.jpg'),
    variant: 'wide',
    width: 1920,
    height: 1080,
  },
  {
    id: 'lakeside-3d-render',
    title: 'Lakeside (3D Render)',
    alt: 'A digitally rendered sunlit mountain reflected in a forest lake.',
    ...getArtImageUrls('Lakeside.jpg'),
    variant: 'square',
    width: 1920,
    height: 1080,
  },

  {
    id: 'still-life-hot-and-cold',
    title: 'Still life of Hot and Cold',
    alt: 'A painted still life of winter clothing, a red bottle, folded blankets, and a toy mouse.',
    ...getArtImageUrls('Still Life of Hot and Cold.webp'),
    variant: 'big',
    width: 2480,
    height: 3616,
  },

  {
    id: 'still-life-of-randomn-things-color',
    title: 'Still life of Randomn things Color',
    alt: 'A painted still life of a duck figure, a tipped cup, stones, and draped fabric.',
    ...getArtImageUrls('Still Life of Random things Color.webp'),
    variant: 'square',
    width: 2550,
    height: 1803,
  },

  {
    id: 'still-life-potrait-of-myself',
    title: 'Still life Potrait of Myself',
    alt: 'A painted self-portrait of an artist wearing a beanie and working at an easel.',
    ...getArtImageUrls('Still Life Potrait of Myself.webp'),
    variant: 'square',
    width: 2550,
    height: 1859,
  },
  {
    id: 'still-life-of-randomn-things-dual-source-lights',
    title: 'Still life of Randomn things Dual Source Lights',
    alt: 'A painted still life of a desk lamp, water bottle, books, and sneakers under two light sources.',
    ...getArtImageUrls('Still Life of Random things Dual Source Lights.webp'),
    variant: 'wide',
    width: 2550,
    height: 1883,
  },
  {
    id: 'still-life-tick-tock',
    title: 'Still Life: Tick Tock',
    alt: 'A grayscale painted still life of clocks, stuffed animals, a bottle, a mug, and a toy car.',
    ...getArtImageUrls('Still Life of Random things Tick Tock.webp'),
    variant: 'tall',
    width: 2300,
    height: 3300,
  },
  {
    id: 'still-life-of-random-things',
    title: 'Still life of Random things',
    alt: 'A grayscale painted still life of books, a small cup, a stuffed dog, boxes, and a bottle.',
    ...getArtImageUrls('Still Life of Random things 2.webp'),
    variant: 'square',
    width: 3088,
    height: 2440,
  },
  {
    id: 'still-life-of-randomn-things-1',
    title: 'Still life of Randomn Things 1',
    alt: 'A grayscale painted still life of toys, a vase, an hourglass, and draped fabric.',
    ...getArtImageUrls('Still Life of Random things1.webp'),
    variant: 'square',
    width: 2367,
    height: 3300,
  },
]

const photoImages: Array<GalleryImage> = [
  {
    id: 'botanical-home',
    title: 'Botanical Home',
    alt: 'A small house with teal shutters and a planted roof inside a greenhouse.',
    ...getPhotoImageUrls('BotanicalHome.webp'),
    variant: 'square',
    width: 5894,
    height: 3929,
  },
  {
    id: 'autumn-greetings',
    title: 'Autumn Greetings',
    alt: 'Decorative pumpkin reading Autumn Greetings on a table against a warm, wooded fall backdrop.',
    ...getPhotoImageUrls('AutumnGreetings.webp'),
    variant: 'wide',
    width: 6000,
    height: 3400,
  },
  {
    id: 'botanical-fields',
    title: 'Botanical Fields',
    alt: 'A greenhouse garden with flowering plants, a small red-roofed house, and a stream.',
    ...getPhotoImageUrls('BotanicalFields.webp'),
    variant: 'big',
    width: 6000,
    height: 4000,
  },

  {
    id: 'good-times-with-george',
    title: 'Good Times with George',
    alt: 'A smiling person wearing glasses outdoors against a softly blurred wooded background.',
    ...getPhotoImageUrls('GoodTimesWithGeorge.webp'),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'purple-bloom',
    title: 'Purple Bloom',
    alt: 'A close-up of a vivid purple flower with dark veins against blurred green leaves.',
    ...getPhotoImageUrls('PurpleBloom.webp'),
    variant: 'square',
    width: 2760,
    height: 2968,
  },
  {
    id: 'lookout-over-capri',
    title: 'Lookout Over Capri',
    alt: 'A coastal hillside town beneath steep cliffs beside deep blue water.',
    ...getPhotoImageUrls('LookOutOverCapri.webp'),
    variant: 'square',
    width: 4032,
    height: 3024,
  },
  {
    id: 'cathedral-facade',
    title: 'Cathedral Facade',
    alt: 'An ornate white-and-gray cathedral facade and dome beneath a bright blue sky.',
    ...getPhotoImageUrls('CoSMotF.webp'),
    variant: 'wide',
    width: 4032,
    height: 3024,
  },

  {
    id: 'early-sunrise',
    title: 'Early Sunrise',
    alt: 'Sunlight shines through a large tree over a grassy field with a small footbridge.',
    ...getPhotoImageUrls('EarllySunRise.webp'),
    variant: 'big',
    width: 2400,
    height: 1600,
  },
  {
    id: 'morning-field',
    title: 'Morning Field',
    alt: 'A grassy path leads through a field toward trees in warm morning light.',
    ...getPhotoImageUrls('MorningField.webp'),
    variant: 'tall',
    width: 2400,
    height: 1600,
  },
  {
    id: 'shades-of-red',
    title: 'Shades of Red',
    alt: 'A red water bottle, red phone, and small red car arranged on a tabletop.',
    ...getPhotoImageUrls('ShadesofRed.webp'),
    variant: 'tall',
    width: 3420,
    height: 4000,
  },
  {
    id: 'simply-white-flower',
    title: 'Simply White Flower',
    alt: 'A cluster of small white flowers with yellow centers against dark green leaves.',
    ...getPhotoImageUrls('SimplyWhiteFlower.webp'),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-osaka-at-dusk',
    title: 'Osaka at Dusk',
    alt: 'Cars pass a brightly lit convenience store beneath city buildings at dusk in Osaka.',
    ...getPhotoImageUrls('20230618_193849.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 3024,
    height: 4032,
  },
  {
    id: 'jp2023-dotonbori-at-night',
    title: 'Dotonbori at Night',
    alt: 'Restaurants and signs illuminate the Dotonbori canal at night in Osaka.',
    ...getPhotoImageUrls('20230618_200111.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 3024,
    height: 4032,
  },
  {
    id: 'jp2023-evening-market-street',
    title: 'Evening Market Street',
    alt: 'Late afternoon sunlight reaches a sloping Japanese street lined with shops and trees.',
    ...getPhotoImageUrls('20230619_174521.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 3024,
    height: 4032,
  },
  {
    id: 'jp2023-torii-path',
    title: 'Torii Path',
    alt: 'A stone path passes beneath rows of orange torii gates surrounded by forest.',
    ...getPhotoImageUrls('20230620_124054.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 3000,
    height: 4000,
  },
  {
    id: 'jp2023-sacred-forest-tree',
    title: 'Sacred Forest Tree',
    alt: 'A twisted tree in dense forest is marked by a sacred rope and white paper streamers.',
    ...getPhotoImageUrls('Tree1.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-bamboo-forest-path',
    title: 'Bamboo Forest Path',
    alt: 'A narrow footpath passes between tall bamboo and trees in a shaded forest.',
    ...getPhotoImageUrls('Forrest3.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 4000,
    height: 6000,
  },
  {
    id: 'jp2023-forest-trail',
    title: 'Forest Trail',
    alt: 'A narrow trail with a wooden railing winds through dense green forest.',
    ...getPhotoImageUrls('20230626_140500.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 3024,
    height: 4032,
  },
  {
    id: 'jp2023-forest-pond',
    title: 'Forest Pond',
    alt: 'A still green pond sits among dense trees beneath a blue, cloud-filled sky.',
    ...getPhotoImageUrls('20230620_124441.webp', japan2023PhotoImagePath),
    variant: 'big',
    width: 4000,
    height: 3000,
  },
  {
    id: 'jp2023-through-the-bamboo',
    title: 'Through the Bamboo',
    alt: 'Sunlit bamboo covers a hillside framed by dark tree trunks in the foreground.',
    ...getPhotoImageUrls('FramedForrest1.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-kyoto-overlook',
    title: 'Kyoto Overlook',
    alt: 'Kyoto Tower rises above the city with a mountain ridge and heavy clouds behind it.',
    ...getPhotoImageUrls('View2.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-riverside-kyoto',
    title: 'Riverside Kyoto',
    alt: 'A riverside path leads toward a bridge and the low skyline of Kyoto.',
    ...getPhotoImageUrls('20230620_160540.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 4032,
    height: 3024,
  },
  {
    id: 'jp2023-purple-hydrangea-close-up',
    title: 'Purple Hydrangea Close-up',
    alt: 'Purple hydrangea petals fill the frame against softly blurred leaves.',
    ...getPhotoImageUrls('20230624_132405.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 3024,
    height: 4032,
  },
  {
    id: 'jp2023-blue-and-yellow-hydrangea',
    title: 'Blue and Yellow Hydrangea',
    alt: 'Blue and pale yellow hydrangea blossoms stand against a dark green background.',
    ...getPhotoImageUrls('BlueandYellowFlower2.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 4916,
    height: 3512,
  },
  {
    id: 'jp2023-purple-hydrangea',
    title: 'Purple Hydrangea',
    alt: 'A round cluster of purple hydrangea blossoms fills the center of the frame.',
    ...getPhotoImageUrls('PurpleFlower1.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 2876,
    height: 2876,
  },
  {
    id: 'jp2023-blue-and-purple-hydrangeas',
    title: 'Blue and Purple Hydrangeas',
    alt: 'Sunlight falls across clusters of blue and purple hydrangeas.',
    ...getPhotoImageUrls('BluePurpleFlower1.webp', japan2023PhotoImagePath),
    variant: 'big',
    width: 5304,
    height: 3768,
  },
  {
    id: 'jp2023-blue-lacecap-hydrangea',
    title: 'Blue Lacecap Hydrangea',
    alt: 'A blue lacecap hydrangea is isolated against softly blurred green leaves.',
    ...getPhotoImageUrls('BlueFlower2.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-pink-hydrangea',
    title: 'Pink Hydrangea',
    alt: 'A bright pink hydrangea cluster is surrounded by glossy green leaves.',
    ...getPhotoImageUrls('SuperPink1.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-lavender-field',
    title: 'Lavender Field',
    alt: 'Purple lavender flowers rise among green stems in bright sunlight.',
    ...getPhotoImageUrls('Lavender1.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-white-hydrangea',
    title: 'White Hydrangea',
    alt: 'A round cluster of white hydrangea blossoms rests among deep green leaves.',
    ...getPhotoImageUrls('WhiteFlowe1.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-museum-in-nara',
    title: 'Museum in Nara',
    alt: 'A historic museum building stands across a lawn framed by pine trees in Nara.',
    ...getPhotoImageUrls('ParkView1.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-white-azalea',
    title: 'White Azalea',
    alt: 'A white azalea with a pink streak blooms among dark green leaves.',
    ...getPhotoImageUrls('WhiteFlower2.webp', japan2023PhotoImagePath),
    variant: 'big',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-deer-at-nara-park',
    title: 'Deer at Nara Park',
    alt: 'An antlered deer rests beneath a tree while other deer graze in Nara Park.',
    ...getPhotoImageUrls('Deer7.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-mount-fuji-neighborhood',
    title: 'Mount Fuji Neighborhood',
    alt: 'Mount Fuji rises behind homes, sculpted trees, and utility lines on a sunny street.',
    ...getPhotoImageUrls('20230702_163913.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 3024,
    height: 4032,
  },
  {
    id: 'jp2023-mount-fuji-and-boats',
    title: 'Mount Fuji and Boats',
    alt: 'Small boats and a wooden dock sit on Lake Kawaguchi beneath Mount Fuji.',
    ...getPhotoImageUrls('Fuji13.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 4000,
    height: 6000,
  },
  {
    id: 'jp2023-fuji-through-the-garden',
    title: 'Fuji Through the Garden',
    alt: 'Mount Fuji appears between garden plants beneath a clear blue sky.',
    ...getPhotoImageUrls('Fuji16.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-fuji-behind-wild-grasses',
    title: 'Fuji Behind Wild Grasses',
    alt: 'Wild grasses stand in focus with Mount Fuji and drifting clouds behind them.',
    ...getPhotoImageUrls('Fuji14.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-boats-by-lake-kawaguchi',
    title: 'Boats by Lake Kawaguchi',
    alt: 'Two overturned blue boats rest in tall grass beside Lake Kawaguchi and Mount Fuji.',
    ...getPhotoImageUrls('FujiBoats2.webp', japan2023PhotoImagePath),
    variant: 'tall',
    width: 4000,
    height: 6000,
  },
  {
    id: 'jp2023-hydrangeas-and-mount-fuji',
    title: 'Hydrangeas and Mount Fuji',
    alt: 'Deep pink hydrangeas stand in focus with Mount Fuji blurred in the distance.',
    ...getPhotoImageUrls('FujiFlower1.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-kawaguchi-panorama',
    title: 'Lake Kawaguchi Panorama',
    alt: 'A panoramic view spans Lake Kawaguchi, Mount Fuji, and the surrounding green hills.',
    ...getPhotoImageUrls('FujiPanorama1.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 10741,
    height: 3308,
  },
  {
    id: 'jp2023-pier-toward-fuji',
    title: 'Pier Toward Fuji',
    alt: 'A narrow pier points across Lake Kawaguchi toward Mount Fuji in a panoramic view.',
    ...getPhotoImageUrls('FujiPanorama2.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 10140,
    height: 3310,
  },
  {
    id: 'jp2023-fuji-shoreline-panorama',
    title: 'Fuji Shoreline Panorama',
    alt: 'Tall shoreline grasses frame a panoramic view of Lake Kawaguchi and Mount Fuji.',
    ...getPhotoImageUrls('FujiPanorama3.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 11596,
    height: 3404,
  },
  {
    id: 'jp2023-shinjuku-reflections',
    title: 'Shinjuku Reflections',
    alt: 'Modern glass buildings reflect the Shinjuku skyline above a stone staircase and torii gate.',
    ...getPhotoImageUrls('MirroBuilding1.webp', japan2023PhotoImagePath),
    variant: 'big',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-waterside-town',
    title: 'Waterside Town',
    alt: 'Traditional buildings and trees reflect across a calm pond beneath a broad blue sky.',
    ...getPhotoImageUrls('PongView4.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 4000,
    height: 6000,
  },
  {
    id: 'jp2023-gundam-through-the-trees',
    title: 'Gundam Through the Trees',
    alt: 'The Unicorn Gundam statue in Odaiba appears through a frame of green leaves.',
    ...getPhotoImageUrls('Gundam1.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-unicorn-gundam',
    title: 'Unicorn Gundam',
    alt: 'The towering white Unicorn Gundam statue stands beneath a clear blue sky in Odaiba.',
    ...getPhotoImageUrls('Gundam6.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-walking-tokyo',
    title: 'Walking Tokyo',
    alt: 'Two people walk down a steep residential street toward high-rise buildings in Tokyo.',
    ...getPhotoImageUrls('Stroll3.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-quiet-city-street',
    title: 'Quiet City Street',
    alt: 'An empty neighborhood street curves between low buildings toward a distant tower.',
    ...getPhotoImageUrls('Stroll4.webp', japan2023PhotoImagePath),
    variant: 'square',
    width: 6000,
    height: 4000,
  },
  {
    id: 'jp2023-green-city-street',
    title: 'Green City Street',
    alt: 'A curving city street passes between dense trees and tall buildings in Tokyo.',
    ...getPhotoImageUrls('Stroll1.webp', japan2023PhotoImagePath),
    variant: 'wide',
    width: 6000,
    height: 4000,
  },
]

export function getArtImages(): Array<GalleryImage> {
  return [...artImages]
}

export function getPhotoImages(): Array<GalleryImage> {
  return [...photoImages]
}
