/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout/index'
import { Route as MainLayoutStyleTestRouteImport } from './routes/_main-layout/style-test'
import { Route as MainLayoutGalleryRouteImport } from './routes/_main-layout/gallery'
import { Route as MainLayoutAboutRouteImport } from './routes/_main-layout/about'
import { Route as MainLayoutGalleryIndexRouteImport } from './routes/_main-layout/gallery/index'
import { Route as MainLayoutProjectsProjectnameRouteImport } from './routes/_main-layout/projects/$projectname'
import { Route as MainLayoutGalleryVideosRouteImport } from './routes/_main-layout/gallery/videos'
import { Route as MainLayoutGalleryPhotosRouteImport } from './routes/_main-layout/gallery/photos'
import { Route as MainLayoutGalleryBentoDemoRouteImport } from './routes/_main-layout/gallery/bento-demo'
import { Route as MainLayoutGalleryArtRouteImport } from './routes/_main-layout/gallery/art'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutStyleTestRoute = MainLayoutStyleTestRouteImport.update({
  id: '/style-test',
  path: '/style-test',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutGalleryRoute = MainLayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAboutRoute = MainLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutGalleryIndexRoute = MainLayoutGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutGalleryRoute,
} as any)
const MainLayoutProjectsProjectnameRoute =
  MainLayoutProjectsProjectnameRouteImport.update({
    id: '/projects/$projectname',
    path: '/projects/$projectname',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutGalleryVideosRoute = MainLayoutGalleryVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => MainLayoutGalleryRoute,
} as any)
const MainLayoutGalleryPhotosRoute = MainLayoutGalleryPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => MainLayoutGalleryRoute,
} as any)
const MainLayoutGalleryBentoDemoRoute =
  MainLayoutGalleryBentoDemoRouteImport.update({
    id: '/bento-demo',
    path: '/bento-demo',
    getParentRoute: () => MainLayoutGalleryRoute,
  } as any)
const MainLayoutGalleryArtRoute = MainLayoutGalleryArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => MainLayoutGalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof MainLayoutAboutRoute
  '/gallery': typeof MainLayoutGalleryRouteWithChildren
  '/style-test': typeof MainLayoutStyleTestRoute
  '/': typeof MainLayoutIndexRoute
  '/gallery/art': typeof MainLayoutGalleryArtRoute
  '/gallery/bento-demo': typeof MainLayoutGalleryBentoDemoRoute
  '/gallery/photos': typeof MainLayoutGalleryPhotosRoute
  '/gallery/videos': typeof MainLayoutGalleryVideosRoute
  '/projects/$projectname': typeof MainLayoutProjectsProjectnameRoute
  '/gallery/': typeof MainLayoutGalleryIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainLayoutAboutRoute
  '/style-test': typeof MainLayoutStyleTestRoute
  '/': typeof MainLayoutIndexRoute
  '/gallery/art': typeof MainLayoutGalleryArtRoute
  '/gallery/bento-demo': typeof MainLayoutGalleryBentoDemoRoute
  '/gallery/photos': typeof MainLayoutGalleryPhotosRoute
  '/gallery/videos': typeof MainLayoutGalleryVideosRoute
  '/projects/$projectname': typeof MainLayoutProjectsProjectnameRoute
  '/gallery': typeof MainLayoutGalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/_main-layout/about': typeof MainLayoutAboutRoute
  '/_main-layout/gallery': typeof MainLayoutGalleryRouteWithChildren
  '/_main-layout/style-test': typeof MainLayoutStyleTestRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/gallery/art': typeof MainLayoutGalleryArtRoute
  '/_main-layout/gallery/bento-demo': typeof MainLayoutGalleryBentoDemoRoute
  '/_main-layout/gallery/photos': typeof MainLayoutGalleryPhotosRoute
  '/_main-layout/gallery/videos': typeof MainLayoutGalleryVideosRoute
  '/_main-layout/projects/$projectname': typeof MainLayoutProjectsProjectnameRoute
  '/_main-layout/gallery/': typeof MainLayoutGalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/gallery'
    | '/style-test'
    | '/'
    | '/gallery/art'
    | '/gallery/bento-demo'
    | '/gallery/photos'
    | '/gallery/videos'
    | '/projects/$projectname'
    | '/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/style-test'
    | '/'
    | '/gallery/art'
    | '/gallery/bento-demo'
    | '/gallery/photos'
    | '/gallery/videos'
    | '/projects/$projectname'
    | '/gallery'
  id:
    | '__root__'
    | '/_main-layout'
    | '/_main-layout/about'
    | '/_main-layout/gallery'
    | '/_main-layout/style-test'
    | '/_main-layout/'
    | '/_main-layout/gallery/art'
    | '/_main-layout/gallery/bento-demo'
    | '/_main-layout/gallery/photos'
    | '/_main-layout/gallery/videos'
    | '/_main-layout/projects/$projectname'
    | '/_main-layout/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/style-test': {
      id: '/_main-layout/style-test'
      path: '/style-test'
      fullPath: '/style-test'
      preLoaderRoute: typeof MainLayoutStyleTestRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/gallery': {
      id: '/_main-layout/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof MainLayoutGalleryRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/about': {
      id: '/_main-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutAboutRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/gallery/': {
      id: '/_main-layout/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof MainLayoutGalleryIndexRouteImport
      parentRoute: typeof MainLayoutGalleryRoute
    }
    '/_main-layout/projects/$projectname': {
      id: '/_main-layout/projects/$projectname'
      path: '/projects/$projectname'
      fullPath: '/projects/$projectname'
      preLoaderRoute: typeof MainLayoutProjectsProjectnameRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/gallery/videos': {
      id: '/_main-layout/gallery/videos'
      path: '/videos'
      fullPath: '/gallery/videos'
      preLoaderRoute: typeof MainLayoutGalleryVideosRouteImport
      parentRoute: typeof MainLayoutGalleryRoute
    }
    '/_main-layout/gallery/photos': {
      id: '/_main-layout/gallery/photos'
      path: '/photos'
      fullPath: '/gallery/photos'
      preLoaderRoute: typeof MainLayoutGalleryPhotosRouteImport
      parentRoute: typeof MainLayoutGalleryRoute
    }
    '/_main-layout/gallery/bento-demo': {
      id: '/_main-layout/gallery/bento-demo'
      path: '/bento-demo'
      fullPath: '/gallery/bento-demo'
      preLoaderRoute: typeof MainLayoutGalleryBentoDemoRouteImport
      parentRoute: typeof MainLayoutGalleryRoute
    }
    '/_main-layout/gallery/art': {
      id: '/_main-layout/gallery/art'
      path: '/art'
      fullPath: '/gallery/art'
      preLoaderRoute: typeof MainLayoutGalleryArtRouteImport
      parentRoute: typeof MainLayoutGalleryRoute
    }
  }
}

interface MainLayoutGalleryRouteChildren {
  MainLayoutGalleryArtRoute: typeof MainLayoutGalleryArtRoute
  MainLayoutGalleryBentoDemoRoute: typeof MainLayoutGalleryBentoDemoRoute
  MainLayoutGalleryPhotosRoute: typeof MainLayoutGalleryPhotosRoute
  MainLayoutGalleryVideosRoute: typeof MainLayoutGalleryVideosRoute
  MainLayoutGalleryIndexRoute: typeof MainLayoutGalleryIndexRoute
}

const MainLayoutGalleryRouteChildren: MainLayoutGalleryRouteChildren = {
  MainLayoutGalleryArtRoute: MainLayoutGalleryArtRoute,
  MainLayoutGalleryBentoDemoRoute: MainLayoutGalleryBentoDemoRoute,
  MainLayoutGalleryPhotosRoute: MainLayoutGalleryPhotosRoute,
  MainLayoutGalleryVideosRoute: MainLayoutGalleryVideosRoute,
  MainLayoutGalleryIndexRoute: MainLayoutGalleryIndexRoute,
}

const MainLayoutGalleryRouteWithChildren =
  MainLayoutGalleryRoute._addFileChildren(MainLayoutGalleryRouteChildren)

interface MainLayoutRouteChildren {
  MainLayoutAboutRoute: typeof MainLayoutAboutRoute
  MainLayoutGalleryRoute: typeof MainLayoutGalleryRouteWithChildren
  MainLayoutStyleTestRoute: typeof MainLayoutStyleTestRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutProjectsProjectnameRoute: typeof MainLayoutProjectsProjectnameRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAboutRoute: MainLayoutAboutRoute,
  MainLayoutGalleryRoute: MainLayoutGalleryRouteWithChildren,
  MainLayoutStyleTestRoute: MainLayoutStyleTestRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutProjectsProjectnameRoute: MainLayoutProjectsProjectnameRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
