/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout/index'
import { Route as MainLayoutAboutRouteImport } from './routes/_main-layout/about'
import { Route as MainLayoutProjectsProjectnameRouteImport } from './routes/_main-layout/projects/$projectname'
import { Route as MainLayoutGalleryBentoDemoRouteImport } from './routes/_main-layout/gallery/bento-demo'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAboutRoute = MainLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutProjectsProjectnameRoute =
  MainLayoutProjectsProjectnameRouteImport.update({
    id: '/projects/$projectname',
    path: '/projects/$projectname',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutGalleryBentoDemoRoute =
  MainLayoutGalleryBentoDemoRouteImport.update({
    id: '/gallery/bento-demo',
    path: '/gallery/bento-demo',
    getParentRoute: () => MainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof MainLayoutAboutRoute
  '/': typeof MainLayoutIndexRoute
  '/gallery/bento-demo': typeof MainLayoutGalleryBentoDemoRoute
  '/projects/$projectname': typeof MainLayoutProjectsProjectnameRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainLayoutAboutRoute
  '/': typeof MainLayoutIndexRoute
  '/gallery/bento-demo': typeof MainLayoutGalleryBentoDemoRoute
  '/projects/$projectname': typeof MainLayoutProjectsProjectnameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/_main-layout/about': typeof MainLayoutAboutRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/gallery/bento-demo': typeof MainLayoutGalleryBentoDemoRoute
  '/_main-layout/projects/$projectname': typeof MainLayoutProjectsProjectnameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/' | '/gallery/bento-demo' | '/projects/$projectname'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/gallery/bento-demo' | '/projects/$projectname'
  id:
    | '__root__'
    | '/_main-layout'
    | '/_main-layout/about'
    | '/_main-layout/'
    | '/_main-layout/gallery/bento-demo'
    | '/_main-layout/projects/$projectname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/about': {
      id: '/_main-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutAboutRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/projects/$projectname': {
      id: '/_main-layout/projects/$projectname'
      path: '/projects/$projectname'
      fullPath: '/projects/$projectname'
      preLoaderRoute: typeof MainLayoutProjectsProjectnameRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/gallery/bento-demo': {
      id: '/_main-layout/gallery/bento-demo'
      path: '/gallery/bento-demo'
      fullPath: '/gallery/bento-demo'
      preLoaderRoute: typeof MainLayoutGalleryBentoDemoRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutAboutRoute: typeof MainLayoutAboutRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutGalleryBentoDemoRoute: typeof MainLayoutGalleryBentoDemoRoute
  MainLayoutProjectsProjectnameRoute: typeof MainLayoutProjectsProjectnameRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAboutRoute: MainLayoutAboutRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutGalleryBentoDemoRoute: MainLayoutGalleryBentoDemoRoute,
  MainLayoutProjectsProjectnameRoute: MainLayoutProjectsProjectnameRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
